version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: currency_bird
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/currency_bird.sql:/currency_bird.sql