CREATE TABLE IF NOT EXISTS `usuario`(
    id BIGINT NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Direccion VARCHAR(255) NOT NULL,
    Sexo enum('FEMENINO','MASCULINO','N/A') NOT NULL,
    PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `referencia`(
    id BIGINT NOT NULL AUTO_INCREMENT,
    Usuario BIGINT NOT NULL,
    Invitaciones BIGINT NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT `user_ibfk_1` FOREIGN KEY (`Usuario`) REFERENCES `usuario` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
